//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Beta.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountBank
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> UserModify { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public bool IsActive { get; set; }
    }
}
