//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Beta.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoriesEntities : DbContext
    {
        public LaboratoriesEntities()
            : base("name=LaboratoriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Access> Accesses { get; set; }
        public virtual DbSet<AccountBank> AccountBanks { get; set; }
        public virtual DbSet<BloodGroup> BloodGroups { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<GroupStock> GroupStocks { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MethodPayment> MethodPayments { get; set; }
        public virtual DbSet<Patien> Patiens { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<Reference> References { get; set; }
        public virtual DbSet<Sender> Senders { get; set; }
        public virtual DbSet<Specialist> Specialists { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<TypeStock> TypeStocks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
