//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Beta.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int Id { get; set; }
        public string CodeLocation { get; set; }
        public string Name { get; set; }
        public short Province { get; set; }
        public short City { get; set; }
        public short District { get; set; }
        public short Locality { get; set; }
    }
}
