//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_Beta.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patien
    {
        public int Id { get; set; }
        public string CodePatien { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string PlaceOfBirth { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string TelpHome { get; set; }
        public string TelpWork { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public int BloodGroupId { get; set; }
        public int EducationId { get; set; }
        public int JobId { get; set; }
        public int LocationId { get; set; }
        public byte[] Picture { get; set; }
        public int UserCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
        public Nullable<int> UserModify { get; set; }
        public Nullable<System.DateTime> DateModify { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
